baseURL = 'https://portablegenguide.com/'
languageCode = 'en-us'
title = 'Portable Generator Guide'
theme = 'PaperMod'

googleAnalytics = "G-7XRR67NZEE"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[pagination]
pagerSize = 10

[params]
env = "production"
description = 'Practical guides for choosing, using, and staying safe with portable generators.'
author = 'Portable Generator Guide'
defaultTheme = 'auto'
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowToc = true

[taxonomies]
category = 'categories'
tag = 'tags'
